// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekcoljkooyvdlwxdnkmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrY29samtvb3l2ZGx3eGRua21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzQwMDIsImV4cCI6MjA1OTExMDAwMn0.4wo7wWFNxAioS4f6pGgiZhW3LR8p4kUK8AJmLrq_acA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);